name: Rmarkdown Build

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: 4.x

    - name: Install dependencies
      run: |
        R -e 'install.packages("rmarkdown")'

    - name: Render Rmarkdown
      run: Rscript -e 'rmarkdown::render("bernic_gbaguidi_IML2.Rmd")'
